# Configuration for auto-labeling PRs based on file changes

# Framework labels
'framework: core':
  - changed-files:
    - any-glob-to-any-file: 'core/**/*'

'framework: remix':
  - changed-files:
    - any-glob-to-any-file: 'remix/**/*'

'framework: next':
  - changed-files:
    - any-glob-to-any-file: 'next/**/*'

'framework: shared':
  - changed-files:
    - any-glob-to-any-file: 'shared/**/*'

# Type labels
'type: documentation':
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.md'
      - 'docs/**/*'

'type: test':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
      - 'tests/**/*'

'type: ci/cd':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/actions/**/*'

'type: config':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.toml'
      - '**/.*rc'

'type: dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - '**/package.json'

# Component type labels
'component: ui':
  - changed-files:
    - any-glob-to-any-file:
      - '**/components/**/*'
      - '**/ui/**/*'

'component: hooks':
  - changed-files:
    - any-glob-to-any-file:
      - '**/hooks/**/*'

'component: utils':
  - changed-files:
    - any-glob-to-any-file:
      - '**/utils/**/*'
      - '**/utilities/**/*'

'component: api':
  - changed-files:
    - any-glob-to-any-file:
      - '**/api/**/*'
      - '**/services/**/*'

# Platform labels
'platform: desktop':
  - changed-files:
    - any-glob-to-any-file:
      - 'desktop/**/*'
      - '**/tauri/**/*'

'platform: mobile':
  - changed-files:
    - any-glob-to-any-file:
      - 'mobile/**/*'
      - '**/capacitor/**/*'

'platform: web':
  - changed-files:
    - any-glob-to-any-file:
      - '**/web/**/*'

# Other labels
'needs review':
  - draft: false

'breaking change':
  - changed-files:
    - any-glob-to-any-file:
      - '**/BREAKING_CHANGES.md'
  - head-branch: ['^breaking', 'breaking']