name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "needs triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Which framework is affected?
      multiple: true
      options:
        - Core
        - Remix
        - Next.js
        - Shared
        - All frameworks
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem.

  - type: input
    id: version
    attributes:
      label: Katalyst React Version
      description: What version of Katalyst React are you using?
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      options:
        - "22.x (latest)"
        - "20.x (LTS)"
        - "18.x"
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser (if applicable)
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
        - Not applicable

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true